ports:
  http: 3000
  sensors: 4000

speaker:
  enabled: true
  id: '3'
  name: 'Speaker start'

tracks:
  - id: '1'
    name: 'Track 1'
    color: '#FF0000'
    sensors:
      - id: '1'
        name: 'Sensor 1'
        type: 'start'
      - id: '2'
        name: 'Sensor 2'
        type: 'finish'
