version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '4000:4000'
      - '5000:5000'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/dst
    volumes:
      - /home/dynamic/dst/master/config:/app/config
    depends_on:
      - db
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - VITE_MASTER_COUNTDOWN_SOCKET_URL=http://backend:3002
      - VITE_MASTER_API_SOCKET_URL=http://backend:3001
      - VITE_MASTER_API_URL=http://backend:3000
    depends_on:
      - backend
    networks:
      - app_network
    restart: always

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dst
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
