version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '4000:4000'
      - '5000:5000'
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@db:5432/dst?schema=public"
    volumes:
      - /home/dynamic/dst/master/config:/app/config
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - backend

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
