services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '4000:4000'
      - '5000:5000'
    environment:
      - DATABASE_URL=mysql://root:root@192.168.50.51:3306/dst
    volumes:
      - /home/dynamic/dst/master/config:/app/config
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_MASTER_COUNTDOWN_SOCKET_URL=http://192.168.50.51:3002
        - VITE_MASTER_API_SOCKET_URL=http://192.168.50.51:3001
        - VITE_MASTER_API_URL=http://192.168.50.51:3000
    ports:
      - '8080:8080'
    depends_on:
      - backend
    restart: always

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dst
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db_data:
