version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '3001:3001'
      - '3002:3002'
      - '4000:4000'
      - '5000:5000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@192.168.50.51:5432/dst?schema=public
    volumes:
      - /home/dynamic/dst/master/config:/app/config
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - VITE_MASTER_COUNTDOWN_SOCKET_URL='http://backend:3002'
      - VITE_MASTER_API_SOCKET_URL='http://backend:3001'
      - VITE_MASTER_API_URL='http://backend:3000'
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
